# Generated by Django 5.1.2 on 2024-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imod', '0002_remove_news_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='custom_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
